name: Build
on:
    push:
        branches:
            - main
        paths:
            - packages/**
            - docs/**
            - rollup.config.js
            - package.json
            - pnpm-lock.yaml
            - .github/workflows/build.yml

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - uses: pnpm/action-setup@v2

            - uses: actions/setup-node@v2
              with:
                  node-version: 19
                  cache: "pnpm"

            - run: pnpm install --frozen-lockfile
            - run: pnpm build

            - name: "asar-ify"
              run: pnpx asar pack dist/ dist/aero.asar

            - name: "Find Hash"
              id: hash
              run: |
                  echo "HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

            - name: "Create Release"
              run: |
                  gh release upload development dist/aero.asar --clobber
                  gh release edit development --title "Development $HASH"
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  HASH: ${{ env.HASH }}
