name: Lint
on:
    push:
        branches:
            - main
        paths:
            - packages/**
            - docs/**
            - rollup.config.js
            - package.json
            - pnpm-lock.yaml
            - .github/workflows/build.yml

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - uses: pnpm/action-setup@v2

            - uses: actions/setup-node@v2
              with:
                  node-version: 19
                  cache: "pnpm"

            - run: pnpm install --frozen-lockfile
            - run: pnpm lint
